name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - 'docs/**/**.puml'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Render
        uses: docker://miy4/plantuml:latest
        with:
          args: "-tsvg -recurse /github/workspace/docs/**/*.puml"
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "wwerner"
          commit_user_email: "mail@wolfgang-werner.net"
          commit_author: "Wolfgang Werner <mail@wolfgang-werner.net>"
          commit_message: "CI - Generate images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}